name: Auto Comment on PR

permissions:
  contents: read
  pull-requests: write

on:
  pull_request_target:
    types: [ opened, synchronize ]
    branches: [ main ]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create a comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo, number: issue_number } = context.issue;
            
            // Get PR creator's username
            const prCreator = context.payload.pull_request.user.login;
            
            const commentBody = `
            🔊@${prCreator} 🚀Thanks for your contribution🎉！
            🔊@${prCreator}🚀感谢你的贡献🎉
            
            💡LemonHelper(AI) will review your code first🔥！
            💡柠檬小助手（AI）将第一个审批你的代码🔥！

            > [!NOTE]
            > 
            > 🚨Code review suggestions from LemonHelper are to be used as a reference only, and the PR submitter can decide whether to make changes based on their own judgment. Ultimately, the project management personnel will conduct the final code review💥.
            > 🚨来自 柠檬小助手 的代码审查建议仅供参考，PR 提交者可以根据自己的判断决定是否进行修改。最终，项目管理人员将进行最终的代码审查💥
            `;
            github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: commentBody
            });
            github.rest.issues.addLabels({
                owner,
                repo,
                issue_number,
                labels: ['ready to review','AI review first','auto merge']
              });
